baseURL = "https://bruteforceboy.github.io/"
languageCode = "en-us"
title = "LearnQuest"
theme = "hugo-book"

[params]
  github = "https://bruteforceboy.github.io/tc-project/"
  # Params for the theme
  BookShowToC = true   # Enable Table of Contents
  BookToC = 3          # Depth of the Table of Contents: adjust if needed

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
    