baseURL = "https://bruteforceboy.github.io/tc-project/"
languageCode = "en-us"
title = "LearnQuest"
theme = "hugo-book"

[params]
  # General params
  github = "https://bruteforceboy.github.io/tc-project/"
  BookShowToC = true   # Enable Table of Contents
  BookToC = 3          # Depth of the Table of Contents: adjust if needed
  BookTheme = "dark"   # Set the theme to dark mode

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

# Menu configuration for sidebar ordering
[[menu.main]]
  identifier = "install"
  name = "Installation Guide"
  url = "/tc-project/docs/install/"
  weight = 1

[[menu.main]]
  identifier = "endpoints"
  name = "Endpoints"
  url = "/tc-project/docs/endpoints/"
  weight = 2

[[menu.main]]
  identifier = "troubleshoot"
  name = "Troubleshooting"
  url = "/tc-project/docs/troubleshoot/"
  weight = 3

[[menu.main]]
  identifier = "faq"
  name = "FAQ"
  url = "/tc-project/docs/faq/"
  weight = 4

[[menu.main]]
  identifier = "contributors"
  name = "Contributors"
  url = "/tc-project/docs/contributors/"
  weight = 5