baseURL = "https://bruteforceboy.github.io/tc-project/"
languageCode = "en-us"
title = "LearnQuest"
theme = "hugo-book"
canonifyURLs = true

[params]
  # General params
  github = "https://bruteforceboy.github.io/tc-project/"
  BookShowToC = true   # Enable Table of Contents
  BookToC = 3          # Depth of the Table of Contents: adjust if needed
  BookTheme = "dark"   # Set the theme to dark mode

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true